DROP TABLE TBL_USER;

CREATE SEQUENCE SEQ_USER
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000;

CREATE TABLE TBL_USER(
	USER_NUMBER NUMBER,
	ID VARCHAR2(20) NOT NULL,
	PW VARCHAR2(20),
	NAME VARCHAR2(20),
	AGE NUMBER,
	PHONE_NUMBER VARCHAR2(12),
	CONSTRAINT PK_USER PRIMARY KEY(USER_NUMBER)
);

SELECT * FROM TBL_USER;

--더미 데이터, 토이 데이터
INSERT INTO TBL_USER
(USER_NUMBER, ID, PW, NAME, AGE, PHONE_NUMBER)
VALUES(SEQ_USER.NEXTVAL, 'user000', '1234', '한동석', 20, '01011112222');

INSERT INTO TBL_USER
(USER_NUMBER, ID, PW, NAME, AGE, PHONE_NUMBER)
VALUES(SEQ_USER.NEXTVAL, 'user001', '1234', '한동석', 20, '01011112222');










